services:
  - type: web
    name: creacipe-backend
    runtime: go
    plan: free
    buildCommand: go build -o app .
    startCommand: ./app
    envVars:
      - key: GIN_MODE
        value: release
